### ISSUE TITLE
Implement Default

### ISSUE THREAD

**Issue by oakwhiz** [ociswap/scrypto-avltree#27]
Minor suggestion, something like this:
```rust
impl<K: Default + Clone + Ord + Display + Hash, V: Default> Default for AvlTree<K, V> {
    fn default() -> Self {
        AvlTree::new()
    }
}
```

**Comment by fpieper** [comment]
@oakwhiz sounds like a good idea. @flix59 what do you mean?

One question, I would be really interested to know more about your project and blueprint you are using the avltree for. You can also write to me on Telegram if you prefer that. Thank you very much in advance 👍

**Comment by flix59** [comment]
Yes i can create a PR for that :+1:

**Comment by flix59** [comment]
https://github.com/ociswap/scrypto-avltree/pull/29
Created a PR here
